export default [
  { id: 'objects-processes', title: 'Objects, processes, and transformation', sample: '01-objects-processes.opl',
    explanation: 'An Object is a thing that exists; a Process transforms objects. "Handling consumes Order." and "Handling yields Handled Order." are transformation links: consumption points into the process, production points out of it.' },
  { id: 'essence-affiliation', title: 'Essence and affiliation', sample: '02-essence-affiliation.opl',
    explanation: 'Essence is physical or informatical; affiliation is systemic or environmental. "Customer is physical and environmental." marks an object outside the system that interacts with it.' },
  { id: 'object-states', title: 'Object states', sample: '03-object-states.opl',
    explanation: 'A stateful object is drawn as a rectangle divided into state compartments. States are listed with "can be", and initial/final states are named explicitly.' },
  { id: 'input-output', title: 'Input-output pair (state change)', sample: '04-input-output.opl',
    explanation: '"Handling changes Order from new to closed." expands into two links: the input state feeds the process, and the process produces the output state.' },
  { id: 'enabling', title: 'Enabling links: agent and instrument', sample: '05-enabling-agent-instrument.opl',
    explanation: 'Enabling links do not transform their source. An agent (a human) is drawn with a filled circle at the process; an instrument with a hollow circle.' },
  { id: 'condition', title: 'Condition link', sample: '06-condition.opl',
    explanation: '"Handling occurs if Order is paid." makes the process conditional on a state of another object, drawn with an open arrow at the process.' },
  { id: 'aggregation', title: 'Aggregation-participation', sample: '07-aggregation.opl',
    explanation: '"Whole consists of A, B, and C." builds the whole-part hierarchy, drawn with a filled triangle pointing at the whole.' },
  { id: 'exhibition', title: 'Exhibition-characterization', sample: '08-exhibition.opl',
    explanation: '"Order exhibits Price." attaches a feature to an object, drawn with a triangle that contains a smaller filled triangle.' },
  { id: 'generalization', title: 'Generalization and classification', sample: '09-generalization-classification.opl',
    explanation: '"Order is a Document." is generalization (hollow triangle to the general); "Special Order is an instance of Order." is classification (triangle containing a dot).' },
  { id: 'tagged', title: 'Tagged structural link', sample: '10-tagged.opl',
    explanation: '"Driver communicates via OnStar Console." is a user-defined tagged link; the tag is rendered along the edge.' },
];
